VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "If_Names"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = True
Option Compare Database
Option Explicit

Public Sub init(entityCode As String)

End Sub

Public Function getName(language As String) As String

End Function

Public Sub saveName(newName As dom_Name, entityType As String)

End Sub
