VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "Names_IF"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = True
Option Compare Database
Option Explicit

Public Function getName(entityCode As String, language As String) As EntityName

End Function

Public Function rsString(entityCode As String) As String

End Function

Public Sub saveName(entityCode As String, newName As EntityName)

End Sub
