VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "Owners_IF"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = True
Option Compare Database
Option Explicit

Public Function getOwner(entityCode As String) As Owner

End Function

Public Sub saveOwner(entityCode As String, newOwner As Owner)

End Sub

Public Function rsStringAll() As String

End Function

Public Function rsString(entityCode As String) As String

End Function
